version: '3.4'

services:
  errorcentral.api:
    image: ${DOCKER_REGISTRY-}errorcentralapi
    enviroment:
      - PORT=5000
    ports:
      - 5000:5000
    build:
      context: .
      dockerfile: Dockerfile

   
   
